---
name: "Set up Vagrant"
description: "Set up Vagrant with Libvirt on GitHub Actions"
inputs:
  configure_dns:
    description: 'Set up a libvirt networking hook to configure systemd-resolved'
    required: false
    type: boolean
runs:
  using: "composite"
  steps:
    - name: 'Install libvirt network hook'
      if: ${{ inputs.configure_dns }}
      shell: bash
      run: |
        sudo install -D -m 0755 ${{ github.action_path }}/network-hook /etc/libvirt/hooks/network
    - id: script
      shell: bash
      run: |
        . /etc/os-release
        if [ "${VERSION_ID}" != "22.04" ]; then
          sudo curl --output /etc/apt/keyrings/evgeni-vagrant-noble.gpg https://people.debian.org/~evgeni/vagrant-noble/evgeni.gpg
          echo "deb [signed-by=/etc/apt/keyrings/evgeni-vagrant-noble.gpg] https://people.debian.org/~evgeni/vagrant-noble/ ./" | sudo tee /etc/apt/sources.list.d/evgeni-vagrant-noble.list
        fi
        echo "man-db man-db/auto-update boolean false" | sudo debconf-set-selections
        sudo dpkg-reconfigure man-db
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends vagrant vagrant-libvirt libvirt-daemon-system libvirt-daemon qemu-system-x86 qemu-utils dnsmasq
        sudo chmod 666 /var/run/libvirt/libvirt-sock
